# Generated by Django 4.2 on 2023-11-08 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realestate', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نوع غذا')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=10000, verbose_name='ادرس')),
                ('how_much_cook', models.IntegerField(verbose_name='توانایی چند پخت درروز را دارید')),
                ('number', models.IntegerField(verbose_name='تعداد')),
                ('date_cook', models.CharField(max_length=1000, verbose_name=' روز هایی میتوانید غذا درست کنید')),
                ('time_cook', models.TimeField(verbose_name='ساعت هایی که می توانید غذا درست کنید')),
                ('master_chef_name', models.CharField(max_length=1000, verbose_name='نام سر اشپز')),
                ('chef_name', models.CharField(max_length=1000, verbose_name='نام اشپز')),
                ('image_1', models.ImageField(upload_to='images/ads/food/image', verbose_name='اپلود عکس از غذا')),
                ('image_2', models.ImageField(upload_to='images/ads/food/image', verbose_name='اپلود عکس از غذا')),
                ('image_3', models.ImageField(upload_to='images/ads/food/image', verbose_name='اپلود عکس از غذا')),
                ('point', models.IntegerField(verbose_name='امتیاز')),
                ('is_public', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='realestate.state', verbose_name='نام استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('what_can_cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='foodapp.cooktype', verbose_name=' نوع غذایی میتوانید درست کنید')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('body', models.TextField(max_length=10000000, verbose_name='جزعیات نظر')),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='foodapp.foodinformation', verbose_name='اگهی اتوبوس')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='foodapp.comment', verbose_name='ریپلای')),
            ],
        ),
    ]
