# Generated by Django 4.2.3 on 2023-11-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="is_Accept_terms",
        ),
        migrations.AddField(
            model_name="otp",
            name="Full_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام کامل"
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(
                default=2, max_length=255, verbose_name="پست الکترونیک"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otp",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="UserImage", verbose_name="عکس کاربر"
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_bus_driver",
            field=models.BooleanField(default=False, verbose_name="راننده ی اتوبوس"),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_realestate",
            field=models.BooleanField(default=False, verbose_name="املاک دار"),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_simple_user",
            field=models.BooleanField(default=False, verbose_name="کاربر ساده"),
        ),
        migrations.AddField(
            model_name="otp",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="نام کاربری",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_bus_driver",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="راننده ی اتوبوس"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_realestate",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="املاک دار"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_simple_user",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="کاربر ساده"
            ),
        ),
    ]
