# Generated by Django 4.2.3 on 2023-11-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_otp_is_accept_terms_otp_full_name_otp_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("-date_added",),
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربرها",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="date_added",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
