# Generated by Django 4.2.3 on 2023-11-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_options_user_date_added_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_chef",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name=" اشپز"
            ),
        ),
    ]
