# Generated by Django 4.2.3 on 2023-11-25 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BedCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="نام تعداد تخت ها"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="نام شهر")),
            ],
        ),
        migrations.CreateModel(
            name="CoolingSystemProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="نام سیستمای سرمایشی "
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntertainmentPossibilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="نام سرگرمی ها "),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvironmentalContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="نام بافت های محیطی"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeatingSystemProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="نام سیستمای گرمایشی "
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KitchenEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="نام تجهیزات اشپز خانه "
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherSpacesResidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="نام دیگر فضاهای اقامتگاه "
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="نام مدل ملک ها"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPossibilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="نام امکانات")),
            ],
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="نام مدل ملک ها "),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomPossibilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="نام امکانات اتاق"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelectionSans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="نام سانس ها "),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="نام استان")),
            ],
        ),
        migrations.CreateModel(
            name="TypeFloorProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="نام نوع کف ها برای ملک ها "
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="مالیکت ها")),
            ],
        ),
        migrations.CreateModel(
            name="WelfarePossibilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="نام اکانات رفاهی "),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=1000, verbose_name="نام ملک"),
                ),
                (
                    "property_address",
                    models.CharField(max_length=1000, verbose_name="ادرس ملک"),
                ),
                ("post_card", models.BigIntegerField(verbose_name="کد پستی")),
                ("property_phone", models.BigIntegerField(verbose_name="تلفن ملک")),
                (
                    "name_property_owner",
                    models.CharField(max_length=1000, verbose_name="نام صاحب ملک"),
                ),
                (
                    "phone_property_manager",
                    models.BigIntegerField(verbose_name="شماره تلفن مدیر ملک"),
                ),
                (
                    "phone_property",
                    models.BigIntegerField(verbose_name="شماره تلفن ملک"),
                ),
                (
                    "square_footage_property",
                    models.IntegerField(verbose_name="متراژ ملک"),
                ),
                (
                    "about_property",
                    models.TextField(
                        blank=True, null=True, verbose_name="درباره ملک(اختیاری)"
                    ),
                ),
                ("created_at_property", models.DateField(verbose_name="ُسال ساخت ملک")),
                (
                    "villa_registration_rules",
                    models.TextField(verbose_name="قوانین ثبت ویلا"),
                ),
                (
                    "capacity_property",
                    models.CharField(max_length=100000, verbose_name="ظرفیت ملک"),
                ),
                (
                    "lease_date",
                    models.DateField(verbose_name="ﺗﺎرﻳﺦاﺟﺎره(ﺗﺎرﻳﺦ ﻫﺎي آزاد)"),
                ),
                (
                    "property_image",
                    models.ImageField(
                        upload_to="images/ads/property", verbose_name="تصاویر ملک"
                    ),
                ),
                (
                    "property_image2",
                    models.ImageField(
                        upload_to="images/ads/property", verbose_name="تصاویر ملک"
                    ),
                ),
                (
                    "property_image3",
                    models.ImageField(
                        upload_to="images/ads/property", verbose_name="تصاویر ملک"
                    ),
                ),
                (
                    "property_image4",
                    models.ImageField(
                        upload_to="images/ads/property", verbose_name="تصاویر ملک"
                    ),
                ),
                ("enter_limit", models.TimeField(verbose_name="محدودیت ورود")),
                ("exit_limit", models.TimeField(verbose_name="محدودیت خروج")),
                (
                    "parking_count",
                    models.SmallIntegerField(verbose_name="تعداد پارکینگ"),
                ),
                ("classes", models.SmallIntegerField(verbose_name="طبقه")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/ads/property/bills",
                        verbose_name="قبض تلفن یا برق یا گاز",
                    ),
                ),
                ("lease_price", models.IntegerField(verbose_name="قیمت اجاره")),
                ("property_number", models.BigIntegerField(verbose_name="شماره ملک")),
                (
                    "days_booking",
                    models.CharField(
                        max_length=1000000000, verbose_name="روز های ازار برای رزرو"
                    ),
                ),
                ("shaba_number", models.BigIntegerField(verbose_name="شماره شبا")),
                ("cart_number", models.BigIntegerField(verbose_name="شماره کارت")),
                ("account_number", models.BigIntegerField(verbose_name="شماره حساب")),
                (
                    "melli_cart",
                    models.ImageField(
                        upload_to="images/ads/property/documents",
                        verbose_name="کارت ملی یا شناسنامه",
                    ),
                ),
                ("discount", models.BooleanField(default=False)),
                (
                    "residence_rules",
                    models.TextField(max_length=100000000, verbose_name="قوانین اقامت"),
                ),
                (
                    "cancel_request",
                    models.TextField(
                        max_length=100000000, verbose_name="قوانین لغو درخواست(کنسلی)"
                    ),
                ),
                ("enter_time", models.TimeField(verbose_name="ساعت ورود")),
                ("exit_time", models.TimeField(verbose_name="ساعت خروج")),
                (
                    "minimum_stay_limit",
                    models.CharField(max_length=100000, verbose_name="حداقل شب اقامت"),
                ),
                (
                    "maximum_stay_limit",
                    models.CharField(max_length=10000, verbose_name="حداکثر مدت اقامت"),
                ),
                (
                    "room_title",
                    models.CharField(max_length=10000, verbose_name="عنوان اتاق"),
                ),
                ("slug", models.SlugField(max_length=1000)),
                ("is_public", models.BooleanField(default=False)),
                ("is_reserve", models.BooleanField(default=False)),
                (
                    "bed_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.bedcount",
                        verbose_name="تعداد تخت ها",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to="realestate.city",
                        verbose_name="شهر",
                    ),
                ),
                (
                    "cooling_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.coolingsystemproperty",
                        verbose_name="سیستم سرمایش ملک",
                    ),
                ),
                (
                    "entertainment_possibilities",
                    models.ManyToManyField(
                        to="realestate.entertainmentpossibilities",
                        verbose_name="ُسرگرمی ها",
                    ),
                ),
                (
                    "environmental_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.environmentalcontext",
                        verbose_name="بافت محیطی",
                    ),
                ),
                (
                    "heating_system_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.heatingsystemproperty",
                        verbose_name="ﺳﻴﺴﺘﻢ گﺮﻣﺎﻳﺶ ملک",
                    ),
                ),
                (
                    "kitchen_equipment",
                    models.ManyToManyField(
                        to="realestate.kitchenequipment",
                        verbose_name="تجهیزات اشپزخانه",
                    ),
                ),
                (
                    "other_spaces_residence",
                    models.ManyToManyField(
                        to="realestate.otherspacesresidence",
                        verbose_name="سایر فضاهای اقامتگاه",
                    ),
                ),
                (
                    "property_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.propertymodel",
                        verbose_name="مدل ملک",
                    ),
                ),
                (
                    "property_possibilities",
                    models.ManyToManyField(
                        to="realestate.propertypossibilities",
                        verbose_name="اﻣﻜﺎﻧﺎت ﻣﻠﻚ",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.propertytype",
                        verbose_name="نوع ملک",
                    ),
                ),
                (
                    "room_possibilities",
                    models.ManyToManyField(
                        to="realestate.roompossibilities", verbose_name="امکانات اتاق"
                    ),
                ),
                (
                    "selection_sans",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.selectionsans",
                        verbose_name="انتخاب سانس",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to="realestate.state",
                        verbose_name="استان",
                    ),
                ),
                (
                    "type_floor_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.typefloorproperty",
                        verbose_name="نوع کف ملک",
                    ),
                ),
                (
                    "type_ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.typeownership",
                        verbose_name="نوع مالکیت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "welfare_possibilities",
                    models.ManyToManyField(
                        to="realestate.welfarepossibilities",
                        verbose_name="امکانات رفاهی",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="نام")),
                ("body", models.TextField(max_length=10000000, verbose_name=" نظر")),
                ("rate", models.IntegerField()),
                (
                    "it_good",
                    models.BooleanField(default=False, verbose_name="پیشنهاد میکنید؟"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply",
                        to="realestate.comment",
                        verbose_name="ریپلای",
                    ),
                ),
                (
                    "property_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="realestate.propertyinformation",
                        verbose_name="اگهی ملک",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realestatecomment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
    ]
