# Generated by Django 4.2 on 2023-11-08 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=20, verbose_name='نام پلاک')),
                ('car_name', models.CharField(max_length=1000, verbose_name='نام ماشین')),
                ('name_car_owner', models.CharField(max_length=1000, verbose_name='نام صاجب خودرو')),
                ('capacity_number', models.CharField(max_length=10000, verbose_name='تعداد ظرفیت')),
                ('granny', models.BooleanField(default=False, verbose_name='سیستم گرمایش')),
                ('cooling', models.BooleanField(default=False, verbose_name='سیستم سرمایش')),
                ('cost', models.IntegerField(verbose_name='هزینه')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('origin', models.CharField(max_length=10000, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=1000, verbose_name='مقصد')),
                ('service_date', models.DateField(verbose_name='مدت تاریخ سرویس دادن')),
                ('entity', models.TimeField(verbose_name='ساعت حرکت')),
                ('time_destination', models.TimeField(verbose_name='ساعت رسیدن به مقصد')),
                ('service_company_name', models.CharField(max_length=10000, verbose_name=' نام شرکت ارائه دهنده سرویس')),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='مدل ماشین')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام رنگ')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='نام وسیله')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('body', models.TextField(max_length=10000000, verbose_name='جزعیات نظر')),
                ('car_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='driverapp.businformation', verbose_name='اگهی اتوبوس')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='driverapp.comment', verbose_name='ریپلای')),
            ],
        ),
        migrations.AddField(
            model_name='businformation',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverapp.carttypes', verbose_name='مدل ماشین'),
        ),
        migrations.AddField(
            model_name='businformation',
            name='device_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='driverapp.color', verbose_name='رنگ وسیله'),
        ),
        migrations.AddField(
            model_name='businformation',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='driverapp.devicetypes', verbose_name='نوع وسیله'),
        ),
        migrations.AddField(
            model_name='businformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
