# Generated by Django 4.2.3 on 2023-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driverapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="it_good",
            field=models.BooleanField(default=False, verbose_name="پیشنهاد میکنید؟"),
        ),
        migrations.AddField(
            model_name="comment",
            name="rate",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
