# Generated by Django 4.2.3 on 2023-11-17 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("driverapp", "0002_comment_it_good_comment_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="businformation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="car_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="driverapp.businformation",
                verbose_name="اگهی اتوبوس",
            ),
        ),
    ]
