# Generated by Django 4.2.3 on 2023-11-25 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="نام شهر")),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="نام استان")),
            ],
        ),
        migrations.CreateModel(
            name="SimpleUserInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                        max_length=550,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "phone_number",
                    models.BigIntegerField(default=0, verbose_name="شماره تلفن"),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "bank_account",
                    models.BigIntegerField(default=0, verbose_name="شماره حساب"),
                ),
                (
                    "full_name_of_account",
                    models.CharField(
                        max_length=550, verbose_name="نام و نام خانوادگی صاحب حساب"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simple_users",
                        to="simpleuser.city",
                        verbose_name="شهر",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simple_users",
                        to="simpleuser.state",
                        verbose_name="استان",
                    ),
                ),
            ],
        ),
    ]
